spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      database: local
server:
  port: 5000
#---
#spring:
#  config:
#    activate:
#      on-profile: nonprod
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: local
#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: local
#---
#logging:
#  level:
#    root: info